"""Add vNext compliance models

Revision ID: 4ddce277344e
Revises: 
Create Date: 2025-09-05 08:39:35.768472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddce277344e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_id', table_name='sources')
    op.drop_table('sources')
    op.drop_table('auditlog')
    op.drop_table('datasource')
    op.drop_index('ix_audit_events_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_export_bundles_id', table_name='export_bundles')
    op.drop_table('export_bundles')
    op.drop_table('account')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_requests_id', table_name='requests')
    op.drop_index('ix_requests_subject_email', table_name='requests')
    op.drop_table('requests')
    op.drop_index('ix_plans_id', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_dsarrequest_request_id', table_name='dsarrequest')
    op.drop_table('dsarrequest')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_accounts_email', table_name='accounts')
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('email_verification_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_reset_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('current_period_start', sa.DATETIME(), nullable=False),
    sa.Column('current_period_end', sa.DATETIME(), nullable=False),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('interval', sa.VARCHAR(length=20), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('canceled_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=7), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('shopify_domain', sa.VARCHAR(), nullable=True),
    sa.Column('shopify_access_token', sa.VARCHAR(), nullable=True),
    sa.Column('woo_site_url', sa.VARCHAR(), nullable=True),
    sa.Column('woo_api_key', sa.VARCHAR(), nullable=True),
    sa.Column('settings', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    op.create_index('ix_accounts_email', 'accounts', ['email'], unique=1)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), nullable=True),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('actor', sa.VARCHAR(length=255), nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_table('dsarrequest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('request_type', sa.VARCHAR(), nullable=False),
    sa.Column('subject_email', sa.VARCHAR(), nullable=False),
    sa.Column('subject_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('additional_info', sa.VARCHAR(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dsarrequest_request_id', 'dsarrequest', ['request_id'], unique=1)
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('max_dsar_requests', sa.INTEGER(), nullable=False),
    sa.Column('max_users', sa.INTEGER(), nullable=False),
    sa.Column('max_sources', sa.INTEGER(), nullable=False),
    sa.Column('features', sa.TEXT(), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_id', 'plans', ['id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('subject_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('subject_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subject_address', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('additional_info', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_subject_email', 'requests', ['subject_email'], unique=False)
    op.create_index('ix_requests_id', 'requests', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(), nullable=False),
    sa.Column('trial_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_bundles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), nullable=False),
    sa.Column('format', sa.VARCHAR(length=4), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('meta_data', sa.TEXT(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_bundles_id', 'export_bundles', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), nullable=True),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('actor', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('meta_data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_id', 'audit_events', ['id'], unique=False)
    op.create_table('datasource',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('config', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), nullable=True),
    sa.Column('details', sa.VARCHAR(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('connection_data', sa.TEXT(), nullable=False),
    sa.Column('last_sync_at', sa.DATETIME(), nullable=True),
    sa.Column('sync_interval', sa.INTEGER(), nullable=True),
    sa.Column('settings', sa.TEXT(), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_id', 'sources', ['id'], unique=False)
    # ### end Alembic commands ###
